name: demint
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - cuda-toolkit
  - faiss-gpu
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - nodejs
